from __future__ import annotations

API_COMPAT_VERSION = "1"
DEPRECATION_POLICY = (
    "Public root-level exports remain stable within an API compatibility version. "
    "Behavior-breaking removals require a deprecation period and a compatibility version change."
)

PUBLIC_API = (
    "__version__",
    "API_COMPAT_VERSION",
    "DEPRECATION_POLICY",
    "PUBLIC_API",
    "App",
    "AppSettings",
    "AppState",
    "deprecated",
    "Identity",
    "AccountRecord",
    "AccountManager",
    "PasswordHasher",
    "PasswordResetManager",
    "AuthBackend",
    "InMemoryAuthBackend",
    "authenticate_with",
    "Request",
    "WebSocket",
    "UploadedFile",
    "Response",
    "JSONResponse",
    "BackgroundTasks",
    "HTTPException",
    "WebSocketException",
    "AdminPanel",
    "AdminModelConfig",
    "Plugin",
    "Model",
    "create_token",
    "verify_token",
    "normalize_identity",
    "has_role",
    "has_permission",
    "build_permission",
    "has_resource_permission",
    "authorize",
    "AuthorizationPolicy",
    "PolicyRegistry",
    "evaluate_policy",
    "require_policy",
    "require_auth",
    "require_role",
    "require_permission",
    "require_resource_permission",
    "cache",
    "cache_get",
    "cache_set",
    "cache_delete",
    "auth_middleware",
    "security_headers_middleware",
    "rate_limit",
    "session_middleware",
    "set_session_value",
    "get_session_value",
    "clear_session",
    "set_session_user",
    "get_session_user",
    "login_user",
    "logout_user",
    "rotate_session",
    "get_csrf_token",
    "validate_csrf",
    "csrf_middleware",
    "SessionStore",
    "InMemorySessionStore",
    "TemplateEngine",
    "mount_static",
    "mount_spa",
    "paginate",
    "get_pagination_params",
    "TestClient",
    "VersionedAPI",
    "GraphQL",
    "JobQueue",
    "JobRecord",
    "DispatchedJob",
    "JobStore",
    "InMemoryJobStore",
    "SQLiteJobStore",
    "DistributedJobQueue",
    "JobWorker",
    "ServiceClient",
    "Base",
    "engine",
    "SessionLocal",
    "init_db",
    "get_db_session",
)

STABLE_MODULES = (
    "fusionframe",
    "fusionframe.db",
    "fusionframe.orm",
)


def is_public_symbol(name: str) -> bool:
    return name in PUBLIC_API
